force-app/main/default/objects/Word_Shuffle__c/fields/Game_Mode__c.field-meta.xml
<CustomField>
    <fullName>Game_Mode__c</fullName>
    <label>Game Mode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GameResultController.cls
public  class GameResultController {
    @AuraEnabled
    public static List<Word_Shuffle__c> getResults(){
        // get current user id
        string userid = UserInfo.getUserId();
        List<Word_shuffle__c> results = [Select Id, Name, Result__c, Game_Mode__c, CreatedDate
                                        FROM Word_Shuffle__c
                                        Where CreatedbyId = :userid
                                        ORDER BY CreatedDate DESC];
        return results;
    }
    
}